### ISSUE TITLE
Error Reading EKS Cluster - Couldn't Find Resource

### ISSUE THREAD

**Issue by sking8484** [hashicorp/learn-terraform-deploy-nginx-kubernetes-provider#8]
Error: reading EKS Cluster(cluster name here): couldn't find resource

I am using a remote back end here, so I have to change the back end to point to terraform cloud. I verified that the resource was running in AWS (I had just run the previous tutorial) but it still wouldn't work. I also verified that the region was correct.

Any help would be appreciated!

**Comment by BrianMMcClain** [comment]
Hi @sking8484! Sorry this issue never got addressed. I'm going through this repo to clean up some of the issues and wanted to see if you still required help on this. For those that may run into this issue in the future, I wanted to share the `terraform_remote_state` data source that I used for this.

```
data "terraform_remote_state" "eks" {
  backend = "remote"

  config = {
    organization = "MY_ORG"
    workspaces = {
      name = "learn-terraform-eks"
    }
  }
}
```

In this case, I have a workspace in HCP Terraform named `learn-terraform-eks` that I deployed an EKS cluster with previously. 

One other thing I wanted to raise is if you are also deploying your workspace that manages the Nginx deployment/service in HCP Terraform as well, you will need to explicitly allow that workspace access to the `learn-terraform-eks` workspace's state. Refer to the [documentation](https://developer.hashicorp.com/terraform/cloud-docs/workspaces/state#remote-state-access-controls) for more details.
